### ISSUE TITLE
Add dynamic js updates to static site

### ISSUE THREAD

**Issue by kevinmarks** [indicativevote/indicative-vote#6]
Theo has the technique here https://codepen.io/theosanderson/pen/ywWXYM?editors=1111

**Comment by kevinmarks** [comment]
done with https://github.com/indicativevote/indicative-vote/commit/81c8d8a16dc2c64f4d5868bb640ff269811d5113 via PR https://github.com/indicativevote/indicative-vote/pull/15

**Comment by kevinmarks** [comment]
I should probably burn in the current time server-side so the counts are using the right timebase, @theosanderson ?

**Comment by theosanderson** [comment]
I'm not sure that helps (the time would have to be the last time my server got a count, which I could supply if you want). My instinct is still to query the real petitions server from the user's machine, and if we start getting major traffic revert if we wish. There have really been no issues with the server recently, and the native site polls more often than once every minute.

**Comment by kevinmarks** [comment]
The live. Version still does that.

**Comment by theosanderson** [comment]
It queries my server not the petitions server as far as I can see - https://github.com/indicativevote/indicative-vote/blob/master/static/updatecounts.js#L7- so the data may be 15 mins out of date.

**Comment by kevinmarks** [comment]
That is better, thank you. I think pulling in the full json with all the constituencies is a bit much, but this is a great compromise. If you want a jquery-free version of the code, do take it back.
